import type { Metadata } from "next";
<<<<<<< Updated upstream
import { Inter, IBM_Plex_Mono } from "next/font/google";
=======
import { Inter, IBM_Plex_Mono, JetBrains_Mono } from "next/font/google";

import { Providers } from "@/components/providers";
>>>>>>> Stashed changes
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Providers } from "@/components/providers";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
  display: "swap", // IMPORTANT: fallback immediately if not loaded
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
<<<<<<< Updated upstream
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "Curate",
  description: "Cloud IDE",
  icons: {
    icon: "/logo.svg",
  },
>>>>>>> Stashed changes
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
<<<<<<< Updated upstream
      <body className={`${inter.variable} ${plexMono.variable} antialiased`}>
=======
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} ${plexMono.variable} antialiased`}
      >
>>>>>>> Stashed changes
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
